name: CI

on:
  push:
    branches:
      - main

jobs:
  Publish:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Publish Release
        uses: Leomotors/auto-publish-release@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
