name: CI

on:
  push:

jobs:
  Build:
    name: Build Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Yarn Cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install Dependencies (Yarn)
        run: yarn install

      - name: Build
        run: yarn build

  Publish:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Publish Release
        uses: Leomotors/auto-publish-release@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
